// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1TZL2vnLpyYbdcjOtX3DA_93UomLcozU',
    appId: '1:87000291885:web:f9477496857c61222a76a4',
    messagingSenderId: '87000291885',
    projectId: 'food-fa54e',
    authDomain: 'food-fa54e.firebaseapp.com',
    storageBucket: 'food-fa54e.appspot.com',
    measurementId: 'G-S24RQC0M20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RJ03rN8DY1zhndIQZuUS6rNx7uRna7s',
    appId: '1:87000291885:android:3c3793a39ccbc3132a76a4',
    messagingSenderId: '87000291885',
    projectId: 'food-fa54e',
    storageBucket: 'food-fa54e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPoAXJANCCee_2sfV38Tpb6ZZPuaIn9iU',
    appId: '1:87000291885:ios:6a508e9976fad23f2a76a4',
    messagingSenderId: '87000291885',
    projectId: 'food-fa54e',
    storageBucket: 'food-fa54e.appspot.com',
    androidClientId: '87000291885-tbepavsu871t7d8vckh0dan1vedbglua.apps.googleusercontent.com',
    iosBundleId: 'com.example.dineUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPoAXJANCCee_2sfV38Tpb6ZZPuaIn9iU',
    appId: '1:87000291885:ios:6a508e9976fad23f2a76a4',
    messagingSenderId: '87000291885',
    projectId: 'food-fa54e',
    storageBucket: 'food-fa54e.appspot.com',
    androidClientId: '87000291885-tbepavsu871t7d8vckh0dan1vedbglua.apps.googleusercontent.com',
    iosBundleId: 'com.example.dineUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1TZL2vnLpyYbdcjOtX3DA_93UomLcozU',
    appId: '1:87000291885:web:32f82a883f36038a2a76a4',
    messagingSenderId: '87000291885',
    projectId: 'food-fa54e',
    authDomain: 'food-fa54e.firebaseapp.com',
    storageBucket: 'food-fa54e.appspot.com',
    measurementId: 'G-H61FL83B9T',
  );
}
